N=input("Enter your name:")
A=input("Enter an adjective:")
T=input("Enter the name of a place:")
W=input("Enter an activity: ")
print(f"My name is {N} and I am always {A}.One day I would like to visit {T}.I enjoy {W} with friends and random people")
